---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.8accb9cd-e7e9-4c04-ad47-244b3de62490

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.7416b969-d6da-4626-87a2-7e97ea1128d7.Boolean.Property
        operator: ne
        operands:
            - "false"
