---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.a758e7be-b198-4de8-8148-40fd28598b92

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.542febb3-7d82-464d-977c-1c552f82a06e.Boolean.Property
        operator: ne
        operands:
            - "false"
