---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.f3e002f6-4c89-492b-910b-868938742747

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.376eb1c6-8374-46f6-a952-434ff61d284a.Boolean.Property
        operator: ne
        operands:
            - "false"
