---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.f1171df0-79f4-40f8-89aa-51dc1dab5c2c

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.540259bb-1aa9-4042-b503-091b01d25c5e.Boolean.Property
        operator: ne
        operands:
            - "false"
