---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.68a5dff4-e118-4d15-8e9a-faa34e9ca422

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.a37ba6f0-823b-4bb1-9959-7b768fb958f4.Boolean.Property
        operator: ne
        operands:
            - "false"
