---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.b4ff1127-edbd-46a3-b8cd-1bfb5bf9d299

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.bd52efb7-2081-4405-bf48-7f3ab31f0f79.Boolean.Property
        operator: ne
        operands:
            - "false"
