---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.f5bea6bd-49c2-4f0f-b69b-46316cf8e81e

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.49547369-3a04-434c-a45b-b9665e6e9ddf.Boolean.Property
        operator: ne
        operands:
            - "false"
