---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.6f7707cb-75ab-425d-8670-d9fbea9e077a

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.0dc13453-3d82-4443-a189-a7edcd55343d.Boolean.Property
        operator: ne
        operands:
            - "false"
