---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.e27964b3-fc9f-410a-956c-db5bd83f165b

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.bd5e685a-cc68-409b-871c-00ba47f39a1f.Boolean.Property
        operator: ne
        operands:
            - "false"
