---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.82ef0527-6051-4a1e-ae5e-33efc4adcf78

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.9b935e1b-0f63-4a4a-863d-b56ac342980d.Boolean.Property
        operator: ne
        operands:
            - "false"
