---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.0af609f1-1bc4-477d-8cf9-41b3fec5bf3c

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.be892d31-abac-40f5-87ed-e0afb7588454.Boolean.Property
        operator: ne
        operands:
            - "false"
