---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.cd957c44-a017-4e3f-8ef0-cbcd90f9d65b

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.c4e12287-75bc-44a3-8133-c2b039d49c91.Boolean.Property
        operator: ne
        operands:
            - "false"
