---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.e6814167-3026-4e6d-9b7a-fb21ad7aab56

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.10d22ee1-8a4a-47c8-8085-eff3163c8261.Boolean.Property
        operator: ne
        operands:
            - "false"
