---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.2d047eee-4685-4eb9-bfe1-1bd439ecc1c6

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.4688a2cd-1ea5-4be8-bcb5-833ac4ec6fd7.Boolean.Property
        operator: ne
        operands:
            - "false"
