---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.3c532844-d7f5-482d-9226-8a544dadceb8

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.1c0d25f5-44a1-432f-b973-92b1c5111d7f.Boolean.Property
        operator: ne
        operands:
            - "false"
