---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.b7b8cee4-602b-4bb6-ba65-49b6308dc3d8

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.30191e97-79bb-4a3c-badd-8810cfc4d631.Boolean.Property
        operator: ne
        operands:
            - "false"
