---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.b239edd3-0de4-4481-b9d9-df48e31529a1

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.066fb486-722c-4678-8daa-a0b6a31fb1ad.Boolean.Property
        operator: ne
        operands:
            - "false"
