---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.41bc503c-3834-48d2-877f-9aac61e70ca0

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.08ed6006-be6c-4971-b83a-70282c647f4a.Boolean.Property
        operator: ne
        operands:
            - "false"
