---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.6ebd1f96-b274-4fa1-bfde-f76fd3b45a7d

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.b959151e-8c13-4dc2-ab9c-37dfd833fdd1.Boolean.Property
        operator: ne
        operands:
            - "false"
