---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.84573646-fdfb-40ad-b25f-f7104b467d2f

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.3a0cf048-f2b2-4470-bead-f81a2b746759.Boolean.Property
        operator: ne
        operands:
            - "false"
