---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.cd9d0a6e-5394-4e13-9513-e9237f358699

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.0b796215-04b0-436b-9bf2-52021dd594ea.Boolean.Property
        operator: ne
        operands:
            - "false"
