---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: Target-group.6ed2b3b3-7418-48d8-ae7c-7579bed8eb6b

description: Target group 1

conditions:
  allOf:
    - property:
        name: Boolean.c6eb9cbe-19c6-4b26-9196-6d1846eed4fe
        operator: ne
        operands:
            - "false"
