---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: Target-group.379a361a-c062-4914-ab3d-cfa70071e264

description: Target group 1

conditions:
  allOf:
    - property:
        name: Boolean.45941480-a0d4-4f0c-9baa-39c46f485b57
        operator: ne
        operands:
            - "false"
