---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: Target-group.9554de8f-eb15-4923-bc07-f7bb2be58e9b

description: Target group 1

conditions:
  allOf:
    - property:
        name: Boolean.f9ca74af-3ab9-445c-89a3-82a537d25d30
        operator: ne
        operands:
            - "false"
